### ISSUE TITLE
Uncaught Error: Connection is closed.

### ISSUE THREAD

**Issue by valerius21** [jbree/ide-clangd#3]
1. Open Any Rust File
2.Edit it

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ide-clangd](https://github.com/jbree/ide-clangd) package 0.1.2

### Stack Trace

Uncaught Error: Connection is closed.

```
At C:\Users\Valerius\.atom\packages\ide-clangd\node_modules\vscode-jsonrpc\lib\main.js:613

Error: Connection is closed.
    at /packages/ide-clangd/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/packages/ide-clangd/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendNotification (/packages/ide-clangd/node_modules/vscode-jsonrpc/lib/main.js:667:13)
    at LanguageClientConnection._sendNotification (/packages/ide-rust/node_modules/atom-languageclient/build/lib/languageclient.js:372:15)
    at LanguageClientConnection.didChangeTextDocument (/packages/ide-rust/node_modules/atom-languageclient/build/lib/languageclient.js:137:10)
    at TextEditorSyncAdapter.sendIncrementalChanges (/packages/ide-rust/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:204:24)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/text-buffer.js:1674:32)
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/text-buffer.js:964:18)
    at TextEditor.transact (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:1811:30)
    at HTMLElement.newCommandListeners.(anonymous function) (~/AppData/Local/atom/app-1.23.3/resources/app/src/register-default-commands.js:683:28)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.3/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.23.3/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -2:57.3.0 application:open-folder (input.hidden-input)
     -2:55 command-palette:toggle (input.hidden-input)
     -2:48.8.0 core:confirm (input.hidden-input)
     -2:48.8.0 window:run-package-specs (input.hidden-input)
     -2:47.7.0 command-palette:toggle (input.hidden-input)
     -2:47.2.0 editor:consolidate-selections (input.hidden-input)
     -2:47.2.0 core:cancel (input.hidden-input)
     -2:30.4.0 core:backspace (input.hidden-input)
     -2:30.3.0 editor:newline (input.hidden-input)
     -2:28.9.0 core:save (input.hidden-input)
     -1:09.5.0 command-palette:toggle (input.hidden-input)
     -1:09.1.0 core:paste (input.hidden-input)
     -1:08.8.0 core:confirm (input.hidden-input)
 12x -1:04.9.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -1:00.3.0 editor:consolidate-selections (input.hidden-input)
     -1:00.3.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.7.1 
atom-prettify 0.1.3 
autoclose-html 0.23.0 
ide-clangd 0.1.2 
ide-cpp 0.0.3 
ide-css 0.2.0 
ide-html 0.4.1 
ide-json 0.1.0 
ide-python 0.5.0 
ide-rust 0.9.1 
ide-vue 0.1.8 
language-rust 0.4.12 
language-vue 0.23.1 
pretty-json 1.6.4 
vue-format 0.4.0 
vue2-autocomplete 0.1.0-alpha.4 
vuejs2-snippets 0.15.0 
```

**Comment by JerrySievert** [comment]
also failing without rust - current tabs open:

* c++
* markdown

saving on the markdown tab causes issues.  once this occurs, the problem persists after `atom` has been restarted.

**Comment by jbree** [comment]
@JerrySievert can you confirm that you're using version 0.3.0 of ide-clangd? More info would be helpful. @valerius21, are you still having this problem with the latest version?

**Comment by JerrySievert** [comment]
0.3.0, yes.  the stack was the same as @valerius21 had - atom found the issue on its own.

I'll grab another stack trace as soon as it starts crashing again.

when it crashes, any external change also causes the error, such as doing a `git commit` - each file change causes the crash dialog to show up (they end up stacking quite a bit).

**Comment by NexAdn** [comment]
Just got the same problem under Arch Linux when working with a C/C++ source tree:
```
Error: Connection is closed.
    at new ConnectionError (/home/adrian/.atom/packages/ide-clangd/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/home/adrian/.atom/packages/ide-clangd/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendNotification (/home/adrian/.atom/packages/ide-clangd/node_modules/vscode-jsonrpc/lib/main.js:667:13)
    at LanguageClientConnection._sendNotification (/home/adrian/.atom/packages/ide-cpp/node_modules/atom-languageclient/build/lib/languageclient.js:242:15)
    at LanguageClientConnection.didChangeWatchedFiles (/home/adrian/.atom/packages/ide-cpp/node_modules/atom-languageclient/build/lib/languageclient.js:143:10)
    at ServerManager.projectFilesChanged (/home/adrian/.atom/packages/ide-cpp/node_modules/atom-languageclient/build/lib/server-manager.js:233:33)
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at didChangeCallback (/usr/lib/atom/src/project.js:377:22)
    at PathWatcher.onNativeEvents (/usr/lib/atom/src/path-watcher.js:524:7)
    at sub.native.onDidChange.events (/usr/lib/atom/src/path-watcher.js:427:58)
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at NSFWNativeWatcher.onEvents (/usr/lib/atom/src/path-watcher.js:158:18)
    at handler (/usr/lib/atom/src/path-watcher.js:267:12)
```

**Comment by JerrySievert** [comment]
back to the error full time:

```
/Users/jerry/.atom/packages/ide-clangd/node_modules/vscode-jsonrpc/lib/main.js:613
Hide Stack Trace
Error: Connection is closed.
    at new ConnectionError (/Users/jerry/.atom/packages/ide-clangd/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/Users/jerry/.atom/packages/ide-clangd/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendNotification (/Users/jerry/.atom/packages/ide-clangd/node_modules/vscode-jsonrpc/lib/main.js:667:13)
    at LanguageClientConnection._sendNotification (/Users/jerry/.atom/packages/ide-cpp/node_modules/atom-languageclient/build/lib/languageclient.js:242:15)
    at LanguageClientConnection.didChangeTextDocument (/Users/jerry/.atom/packages/ide-cpp/node_modules/atom-languageclient/build/lib/languageclient.js:131:10)
    at TextEditorSyncAdapter.sendFullChanges (/Users/jerry/.atom/packages/ide-cpp/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:181:22)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at disposables.add.displayLayer.onDidChange.changes (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:595:26)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.emitDeferredChangeEvents (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:819:26)
    at DisplayLayer.didChange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:814:57)
    at languageModeDisposable.buffer.languageMode.onDidChangeHighlighting (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:157:18)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextMateLanguageMode.tokenizeNextChunk (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:312:26)
    at _.defer (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:279:63)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/underscore/underscore.js:666:53
```

**Comment by jbree** [comment]
Anyone still having these issues? If so, would like to know which version of clangd you're running. Version included with llvm+clang 6.0.0 has been very stable for me.

**Comment by NexAdn** [comment]
I don't have this error anymore with `cquery-git` (AUR) 1947-af7f14cc and clang/llvm both 6.0.1.

**Comment by JerrySievert** [comment]
still having issues:

clangd version 7.0.0 (tags/RELEASE_700/final)
